name: adoptionapp
description: View pets that are up for adoption.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts: 
  - family: Ubuntu
    fonts: 
    - asset: fonts/Ubuntu-Regular.ttf
    - asset: fonts/Ubuntu-Bold.ttf
